[package]
name = "sparky_extras"
version = "0.1.0"

[lib]
name = "sk_launcher"
crate-type = ["staticlib"]
path = "src/sk_launcher.rs"

[[bin]]
name = "sk_editor"
path = "src/sk_editor.rs"

[dependencies]
eframe = "0.27.1"
image = "0.25.1"
libc = "0.2.154"
